evaluation_system/course/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

	url(r'^addcourse/$', 
		views.AddCourseView.as_view(), 
		name='addcourse'
	),	
]

evaluation_system/dashboard/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(
        r'^dashboard$',
        views.DashboardView.as_view(), 
		name='dashboard'
    ),
	url(
        r'^dashboard/(?P<course_id>[0-9]+)$',
        views.SetCourseDashboardView.as_view(), 
		name='coursedash'
    ),
    url(
        r'^dashboard/(?P<course_id>[0-9]+)/(?P<eva_id>[0-9]+)$',
        views.SetCourseDashboardView.as_view(), 
        name='evadash'
    ),
]

evaluation_system/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
#from users import views

urlpatterns = [
    url(
        '^', 
        include('django.contrib.auth.urls')
    ),
    url(
        r'^admin/', 
        include(admin.site.urls)
    ),
    url(
        r'^',
        include('evaluation_system.users.urls')
    ),
    url(
        r'^',
        include('evaluation_system.evaluation.urls')
    ),
    url(
        r'^',
        include('evaluation_system.course.urls')
    ),
    url(
        r'^',
        include('evaluation_system.questions.urls')
    ),
    url(
        r'^',
        include('evaluation_system.dashboard.urls')
    ),
    url(
        r'^',
        include('evaluation_system.reports.urls')
    ),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

evaluation_system/course/models.py
from django.db import models
from ..users.models import User
from ..questions.models import Question
#from ..evaluation.models import Evaluation
# Create your models here.

class Course(models.Model):
	name = models.CharField(max_length=200)
	professor = models.ManyToManyField(User, limit_choices_to= {'type':'professor'}, related_name = 'professor', through= "Course_User")

	def __unicode__(self):
		return self.name
		
class Course_User(models.Model):
	course = models.ForeignKey(Course)
	professor = models.ForeignKey(User)

evaluation_system/dashboard/models.py
from django.db import models

# Create your models here.

evaluation_system/evaluation/models.py
from django.db import models
from djangoyearlessdate.models import YearField
from ..questions.models import Question
from ..course.models import Course
from ..users.models import User
import datetime

# Create your models here.
class Evaluation(models.Model):
	name = models.CharField(max_length= 200, default = 'Unknown')
	academic_year = YearField(default = datetime.date.today().strftime("%Y"))
	course = models.ForeignKey(Course)
	semester = models.IntegerField()
	seccion = models.CharField(max_length= 3)
	questions = models.ManyToManyField(Question, through = "Evaluation_Question")
	created_by = models.IntegerField(null=True)

	def __unicode__(self):
		return self.name

	def group_names(self):
		return ', '.join([a.name for a in self.groups.all()])
	group_names.short_description = "Group names"


class Evaluation_Question(models.Model):
	evaluation = models.ForeignKey(Evaluation)
	question = models.ForeignKey(Question)

	def __unicode__(self):
		return self.question.question_text

class Group(models.Model):
	name = models.CharField(max_length=200)
	students = models.ManyToManyField(User, limit_choices_to= {'type':'student'}, through = "Group_User", related_name = 'group')
	evaluation = models.ForeignKey(Evaluation, related_name = 'groups') 


	#Method added for displaying all students of the group in the admin page ManyToMany 
	def student_names(self):
		return ', '.join([a.first_name for a in self.students.all()])
	student_names.short_description = "Student names"


	@property
	def done(self):
		count = len(self.group_user_set.all())
		if count > 1:
			for i, group in enumerate(self.group_user_set.all()):
				if not group.done:
					return False
				elif i + 1 == count:
					return True
		elif not self.group_user_set.all()[0].done:
			return False
		else:
			return True



	def __unicode__(self):
		return self.name


class Group_User(models.Model):
	group = models.ForeignKey(Group)
	student = models.ForeignKey(User, limit_choices_to= {'type':'student'})
	done = models.BooleanField(default = False)
	class Meta:
		unique_together = ("group", "student")
	def __unicode__(self):
		return self.group.name

	@property
	def score(self):
		sum = 0
		totalque = 0
		for que in self.group.evaluation.questions.all():
			for answer in que.answer_set.all():
				if answer.student_evaluated == self.student.id:
					sum += answer.score
					totalque += 1
		return str(sum) + '/' + str(totalque * 5)

	@property
	def check_user(self):
		return self.group.evaluation.questions.all()[0].answer_set.all().filter(student_evaluated = self.student.id)[0].student




	

evaluation_system/course/forms.py
from django import forms
from .models import Course

class CourseForm(forms.ModelForm):
	class Meta:
		model = Course
		fields = ['name']

evaluation_system/course/views.py
from django.views.generic import TemplateView
from django.shortcuts import redirect
from .forms import CourseForm
from models import Course_User, Course

# Create your views here.
class AddCourseView(TemplateView):
	template_name = 'dashboard/addcourse.html'

	def post(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect("/login")
		context = self.get_context_data(**kwargs)
		form = CourseForm(request.POST)

		if form.is_valid():
			new_course = form.save()

			professor_course = Course_User(course = new_course, professor = request.user)
			professor_course.save()
			return redirect("/dashboard")
			context["form"] = form
			context["success"] = "Course created"
		else:
			context["form"] = form
			context["error"] = "Course failed"
		return self.render_to_response(context)

	def get(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect("/login")	
		if not request.user.type == "professor":
			return redirect("/")		
		context = self.get_context_data(**kwargs)

		form = CourseForm()

		context['form'] = form

		#context = self.retrieve_persons(request.user, context)
		return self.render_to_response(context)

evaluation_system/dashboard/views.py
from django.shortcuts import redirect
from django.views.generic import TemplateView
from ..course.models import Course
from ..evaluation.models import Evaluation
# Create your views here.
class DashboardView(TemplateView):
	template_name = "dashboard/courses.html"

	def post(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect("/login")
		context = self.get_context_data(**kwargs)
		
		return self.render_to_response(context)

	def get(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect("/login")		
		context = self.get_context_data(**kwargs)

		courses = Course.objects.filter(professor= request.user)
		context['courses'] = courses

		if 'course_id' in request.session:
			del request.session['course_id']
			del request.session['course_name']
		if 'eva_id' in request.session:
			del request.session['eva_id']
			del request.session['eva_name']


		#context = self.retrieve_persons(request.user, context)
		return self.render_to_response(context)

class SetCourseDashboardView(TemplateView):

	def get(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect("/login")		
		context = self.get_context_data(**kwargs)
		if 'eva_id' in request.session:
			del request.session['eva_id']
			del request.session['eva_name']
		if 'course_id' in kwargs:
			request.session['course_id'] = kwargs['course_id']
			request.session['course_name'] = Course.objects.get(pk= kwargs['course_id']).name
		if 'eva_id' in kwargs:
			request.session['eva_id'] = kwargs['eva_id']
			request.session['eva_name'] = Evaluation.objects.get(pk= kwargs['eva_id']).name
		return redirect("/evaluate")





		#context = self.retrieve_persons(request.user, context)
		return self.render_to_response(context)

templates/dashboard/addcourse.html
{% extends 'dashboard/index.html' %}
{% block inside %}
  {% include 'course/addcourse.html' %}
{% endblock %}

templates/dashboard/addgroup.html
{% extends 'dashboard/index.html' %}
{% block inside %}
  {% include 'group/addgroup.html' %}
{% endblock %}

templates/dashboard/addquestion.html
{% extends 'dashboard/index.html' %}
{% block inside %}
  {% include 'question/addquestion.html' %}
{% endblock %}

templates/dashboard/addstudent.html
{% extends 'dashboard/index.html' %}
{% block inside %}
  {% include 'user/addstudent.html' %}
{% endblock %}

templates/dashboard/courses.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron">
<nav>
	<h3>Escoja el curso</h3>
  <ul class="nav nav-pills nav-stacked text-center">
  	{% for course in courses %}
  	<!-- Split button -->
<div class="btn-group">
  <a class= "btn btn-default"href="/dashboard/{{course.id}}">{{course}}</a>
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu">
    {% for eva in course.evaluation_set.all %}
    {% if eva.created_by == request.user.id%}
    <li><a href="/dashboard/{{course.id}}/{{eva.id}}">{{eva}}</a></li>
    {% endif %}
    {% endfor %}
  </ul>
</div>
  	
    {% endfor %}
  </ul>
</nav>
<a href="/addcourse/">Presione aqui para crear un curso</a>
</div>
{% endblock %}

templates/dashboard/evaluate.html
{% extends 'dashboard/index.html' %}
{% block inside %}
  {% include 'evaluation/evaluate.html' %}
{% endblock %}

templates/dashboard/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar" id="sideBar">
          <ul class="nav nav-sidebar">
            {% if not request.session.course_id %}
            <li><a href="{% url 'addcourse'%}">Crear Curso</a></li>
            {% else %}
            <li><h3><a class="" href="{% url 'dashboard' %}">{{ request.session.course_name }} - {{ request.session.eva_name}}</a></h3></li>
            <li><a href="{% url 'evaluate'%}">Crear Evaluacion<span class="sr-only">(current)</span></a></li>

            <li><a href="{% url 'addgroup'%}">Crear Grupo</a></li>
            {% if request.session.eva_id %}
            <li><a href="{% url 'addstudent'%}">Crear Estudiante</a></li>
            {% endif %}
            <li><a href="{% url 'addquestion'%}">Crear Preguntas</a></li>
            {% endif %}
            
          </ul>
        </div>

        <div id="page-wrapper">
            <div class="container-fluid">

                <div class="row">

                    <div class="col-lg-10 pagedash">
                        {% block inside %}
                        {% endblock %}
                    </div>
                </div>
                </div> 
            </div>
        </div>
    </div>


{% endblock %}

{% block extra_css %}

    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}"/>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/createInforme.js' %}"></script>
{% endblock %}